#desc "builds cartagen.js"
#task :build do
#	build
#end

desc "builds cartagen.js for a specific release version"
task :build, :version do |t, args|
  build args.version
end

		
desc "automatically builds cartagen.js when something in src/ changes"
task :autobuild do
	require 'lib/filesystemwatcher'
	watcher = FileSystemWatcher.new
	watcher.addDirectory 'src', '**/*.js'
	watcher.sleepTime = 2
	watcher.start do |status,file|
	    if ([FileSystemWatcher::CREATED,
	    	FileSystemWatcher::MODIFIED,
	    	FileSystemWatcher::DELETED].include? status)
	        
	        build
	    end
	end
	
	watcher.join()
end

desc "builds the API docs"
task :docs do
	Dir.chdir 'lib/jsdoc-toolkit'
	puts `java -jar jsrun.jar app/run.js -v -t=templates/outline/ -d=../../../docs/ -a -r=3 ../../src/`
end

desc "Finds which file a source line is in"
task :which, :line do |t, args|
	lines = Marshal.load IO.read('.line_data.dat')
	puts lines[args.line.to_i]
end


def build(version = nil)
	puts 'building... ' + DateTime.now.to_s
  
  # change constants
  
  constants = YAML.load_file 'src/constants.yml'
  constants['BUILD_DATE'] = DateTime.now.to_s
  if version
    old_version = constants['VERSION']
    constants['VERSION'] = version
  end
  File.open 'src/constants.yml', 'w' do |f|
    f.print(YAML.dump constants)
  end
  
	$:.push 'lib/sprockets'
	require 'sprockets'
	
	secretary = Sprockets::Secretary.new(
	  :load_path    => ['src'],
	  :source_files => ['src/cartagen.js']
	)
	
	lines = Marshal.dump secretary.preprocessor.lines
	File.open '.line_data.dat', 'w' do |f|
		f.print lines
	end
	
	concatenation = secretary.concatenation
	
	concatenation.save_to("cartagen.js")
	
  if version
    constants = YAML.load_file 'src/constants.yml'
    if version
      constants['VERSION'] = old_version
    end
    File.open 'src/constants.yml', 'w' do |f|
      f.print(YAML.dump constants)
    end
  end
  
	puts "Build finished"
end 
